services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      #- ./config.ini:/etc/grafana/grafana.ini
      - ./data:/var/lib/grafana
      #- ./home:/usr/share/grafana
      - ./log:/var/log/grafana
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      HOSTNAME: "localhost"
      GF_SERVER_ROOT_URL: "http://localhost:31009/"
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "smtp-host.site.com:23"
      GF_SMTP_USER: ""
      GF_SMTP_PASSWORD: ""
      GF_SMTP_FROM_ADDRESS: "mail@mail.com"
      GF_SMTP_FROM_NAME: "Grafana"
      GF_SMTP_SKIP_VERIFY: "true"
    restart: always

networks:
  default:
    external: true
    name: intranet
